<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Sushi\Sushi;

class Country extends Model
{
    use Sushi;

    protected $rows;

    public function __construct(array $attributes = [])
    {
        $this->rows = [
            ['code' => 'AF', 'label' => __('Afghanistan')],
            ['code' => 'AX', 'label' => __('Aland Islands')],
            ['code' => 'AL', 'label' => __('Albania')],
            ['code' => 'DZ', 'label' => __('Algeria')],
            ['code' => 'AS', 'label' => __('American Samoa')],
            ['code' => 'AD', 'label' => __('Andorra')],
            ['code' => 'AO', 'label' => __('Angola')],
            ['code' => 'AI', 'label' => __('Anguilla')],
            ['code' => 'AQ', 'label' => __('Antarctica')],
            ['code' => 'AG', 'label' => __('Antigua and Barbuda')],
            ['code' => 'AR', 'label' => __('Argentina')],
            ['code' => 'AM', 'label' => __('Armenia')],
            ['code' => 'AW', 'label' => __('Aruba')],
            ['code' => 'AU', 'label' => __('Australia')],
            ['code' => 'AT', 'label' => __('Austria')],
            ['code' => 'AZ', 'label' => __('Azerbaijan')],
            ['code' => 'BS', 'label' => __('Bahamas')],
            ['code' => 'BH', 'label' => __('Bahrain')],
            ['code' => 'BD', 'label' => __('Bangladesh')],
            ['code' => 'BB', 'label' => __('Barbados')],
            ['code' => 'BY', 'label' => __('Belarus')],
            ['code' => 'BE', 'label' => __('Belgium')],
            ['code' => 'BZ', 'label' => __('Belize')],
            ['code' => 'BJ', 'label' => __('Benin')],
            ['code' => 'BM', 'label' => __('Bermuda')],
            ['code' => 'BT', 'label' => __('Bhutan')],
            ['code' => 'BO', 'label' => __('Bolivia')],
            ['code' => 'BQ', 'label' => __('Bonaire, Sint Eustatius and Saba')],
            ['code' => 'BA', 'label' => __('Bosnia and Herzegovina')],
            ['code' => 'BW', 'label' => __('Botswana')],
            ['code' => 'BV', 'label' => __('Bouvet Island')],
            ['code' => 'BR', 'label' => __('Brazil')],
            ['code' => 'IO', 'label' => __('British Indian Ocean Territory')],
            ['code' => 'BN', 'label' => __('Brunei Darussalam')],
            ['code' => 'BG', 'label' => __('Bulgaria')],
            ['code' => 'BF', 'label' => __('Burkina Faso')],
            ['code' => 'BI', 'label' => __('Burundi')],
            ['code' => 'KH', 'label' => __('Cambodia')],
            ['code' => 'CM', 'label' => __('Cameroon')],
            ['code' => 'CA', 'label' => __('Canada')],
            ['code' => 'CV', 'label' => __('Cape Verde')],
            ['code' => 'KY', 'label' => __('Cayman Islands')],
            ['code' => 'CF', 'label' => __('Central African Republic')],
            ['code' => 'TD', 'label' => __('Chad')],
            ['code' => 'CL', 'label' => __('Chile')],
            ['code' => 'CN', 'label' => __('China')],
            ['code' => 'CX', 'label' => __('Christmas Island')],
            ['code' => 'CC', 'label' => __('Cocos (Keeling) Islands')],
            ['code' => 'CO', 'label' => __('Colombia')],
            ['code' => 'KM', 'label' => __('Comoros')],
            ['code' => 'CG', 'label' => __('Congo')],
            ['code' => 'CD', 'label' => __('Congo, Democratic Republic')],
            ['code' => 'CK', 'label' => __('Cook Islands')],
            ['code' => 'CR', 'label' => __('Costa Rica')],
            ['code' => 'CI', 'label' => __('Cote D\'Ivoire')],
            ['code' => 'HR', 'label' => __('Croatia')],
            ['code' => 'CU', 'label' => __('Cuba')],
            ['code' => 'CW', 'label' => __('Curaçao')],
            ['code' => 'CY', 'label' => __('Cyprus')],
            ['code' => 'CZ', 'label' => __('Czech Republic')],
            ['code' => 'DK', 'label' => __('Denmark')],
            ['code' => 'DJ', 'label' => __('Djibouti')],
            ['code' => 'DM', 'label' => __('Dominica')],
            ['code' => 'DO', 'label' => __('Dominican Republic')],
            ['code' => 'EC', 'label' => __('Ecuador')],
            ['code' => 'EG', 'label' => __('Egypt')],
            ['code' => 'SV', 'label' => __('El Salvador')],
            ['code' => 'GQ', 'label' => __('Equatorial Guinea')],
            ['code' => 'ER', 'label' => __('Eritrea')],
            ['code' => 'EE', 'label' => __('Estonia')],
            ['code' => 'ET', 'label' => __('Ethiopia')],
            ['code' => 'FK', 'label' => __('Falkland Islands (Malvinas)')],
            ['code' => 'FO', 'label' => __('Faroe Islands')],
            ['code' => 'FJ', 'label' => __('Fiji')],
            ['code' => 'FI', 'label' => __('Finland')],
            ['code' => 'FR', 'label' => __('France')],
            ['code' => 'GF', 'label' => __('French Guiana')],
            ['code' => 'PF', 'label' => __('French Polynesia')],
            ['code' => 'TF', 'label' => __('French Southern Territories')],
            ['code' => 'GA', 'label' => __('Gabon')],
            ['code' => 'GM', 'label' => __('Gambia')],
            ['code' => 'GE', 'label' => __('Georgia')],
            ['code' => 'DE', 'label' => __('Germany')],
            ['code' => 'GH', 'label' => __('Ghana')],
            ['code' => 'GI', 'label' => __('Gibraltar')],
            ['code' => 'GR', 'label' => __('Greece')],
            ['code' => 'GL', 'label' => __('Greenland')],
            ['code' => 'GD', 'label' => __('Grenada')],
            ['code' => 'GP', 'label' => __('Guadeloupe')],
            ['code' => 'GU', 'label' => __('Guam')],
            ['code' => 'GT', 'label' => __('Guatemala')],
            ['code' => 'GG', 'label' => __('Guernsey')],
            ['code' => 'GN', 'label' => __('Guinea')],
            ['code' => 'GW', 'label' => __('Guinea-Bissau')],
            ['code' => 'GY', 'label' => __('Guyana')],
            ['code' => 'HT', 'label' => __('Haiti')],
            ['code' => 'HM', 'label' => __('Heard Island and Mcdonald Islands')],
            ['code' => 'VA', 'label' => __('Holy See (Vatican City State)')],
            ['code' => 'HN', 'label' => __('Honduras')],
            ['code' => 'HK', 'label' => __('Hong Kong')],
            ['code' => 'HU', 'label' => __('Hungary')],
            ['code' => 'IS', 'label' => __('Iceland')],
            ['code' => 'IN', 'label' => __('India')],
            ['code' => 'ID', 'label' => __('Indonesia')],
            ['code' => 'IR', 'label' => __('Iran, Islamic Republic Of')],
            ['code' => 'IQ', 'label' => __('Iraq')],
            ['code' => 'IE', 'label' => __('Ireland')],
            ['code' => 'IM', 'label' => __('Isle Of Man')],
            ['code' => 'IL', 'label' => __('Israel')],
            ['code' => 'IT', 'label' => __('Italy')],
            ['code' => 'JM', 'label' => __('Jamaica')],
            ['code' => 'JP', 'label' => __('Japan')],
            ['code' => 'JE', 'label' => __('Jersey')],
            ['code' => 'JO', 'label' => __('Jordan')],
            ['code' => 'KZ', 'label' => __('Kazakhstan')],
            ['code' => 'KE', 'label' => __('Kenya')],
            ['code' => 'KI', 'label' => __('Kiribati')],
            ['code' => 'KP', 'label' => __('Korea, Democratic People\'s Republic Of')],
            ['code' => 'KR', 'label' => __('Korea')],
            ['code' => 'XK', 'label' => __('Kosovo')],
            ['code' => 'KW', 'label' => __('Kuwait')],
            ['code' => 'KG', 'label' => __('Kyrgyzstan')],
            ['code' => 'LA', 'label' => __('Lao People\'s Democratic Republic')],
            ['code' => 'LV', 'label' => __('Latvia')],
            ['code' => 'LB', 'label' => __('Lebanon')],
            ['code' => 'LS', 'label' => __('Lesotho')],
            ['code' => 'LR', 'label' => __('Liberia')],
            ['code' => 'LY', 'label' => __('Libya')],
            ['code' => 'LI', 'label' => __('Liechtenstein')],
            ['code' => 'LT', 'label' => __('Lithuania')],
            ['code' => 'LU', 'label' => __('Luxembourg')],
            ['code' => 'MO', 'label' => __('Macao')],
            ['code' => 'MK', 'label' => __('Macedonia')],
            ['code' => 'MG', 'label' => __('Madagascar')],
            ['code' => 'MW', 'label' => __('Malawi')],
            ['code' => 'MY', 'label' => __('Malaysia')],
            ['code' => 'MV', 'label' => __('Maldives')],
            ['code' => 'ML', 'label' => __('Mali')],
            ['code' => 'MT', 'label' => __('Malta')],
            ['code' => 'MH', 'label' => __('Marshall Islands')],
            ['code' => 'MQ', 'label' => __('Martinique')],
            ['code' => 'MR', 'label' => __('Mauritania')],
            ['code' => 'MU', 'label' => __('Mauritius')],
            ['code' => 'YT', 'label' => __('Mayotte')],
            ['code' => 'MX', 'label' => __('Mexico')],
            ['code' => 'FM', 'label' => __('Micronesia, Federated States Of')],
            ['code' => 'MD', 'label' => __('Moldova')],
            ['code' => 'MC', 'label' => __('Monaco')],
            ['code' => 'MN', 'label' => __('Mongolia')],
            ['code' => 'ME', 'label' => __('Montenegro')],
            ['code' => 'MS', 'label' => __('Montserrat')],
            ['code' => 'MA', 'label' => __('Morocco')],
            ['code' => 'MZ', 'label' => __('Mozambique')],
            ['code' => 'MM', 'label' => __('Myanmar')],
            ['code' => 'NA', 'label' => __('Namibia')],
            ['code' => 'NR', 'label' => __('Nauru')],
            ['code' => 'NP', 'label' => __('Nepal')],
            ['code' => 'NL', 'label' => __('Netherlands')],
            ['code' => 'NC', 'label' => __('New Caledonia')],
            ['code' => 'NZ', 'label' => __('New Zealand')],
            ['code' => 'NI', 'label' => __('Nicaragua')],
            ['code' => 'NE', 'label' => __('Niger')],
            ['code' => 'NG', 'label' => __('Nigeria')],
            ['code' => 'NU', 'label' => __('Niue')],
            ['code' => 'NF', 'label' => __('Norfolk Island')],
            ['code' => 'MP', 'label' => __('Northern Mariana Islands')],
            ['code' => 'NO', 'label' => __('Norway')],
            ['code' => 'OM', 'label' => __('Oman')],
            ['code' => 'PK', 'label' => __('Pakistan')],
            ['code' => 'PW', 'label' => __('Palau')],
            ['code' => 'PS', 'label' => __('Palestinian Territory, Occupied')],
            ['code' => 'PA', 'label' => __('Panama')],
            ['code' => 'PG', 'label' => __('Papua New Guinea')],
            ['code' => 'PY', 'label' => __('Paraguay')],
            ['code' => 'PE', 'label' => __('Peru')],
            ['code' => 'PH', 'label' => __('Philippines')],
            ['code' => 'PN', 'label' => __('Pitcairn')],
            ['code' => 'PL', 'label' => __('Poland')],
            ['code' => 'PT', 'label' => __('Portugal')],
            ['code' => 'PR', 'label' => __('Puerto Rico')],
            ['code' => 'QA', 'label' => __('Qatar')],
            ['code' => 'RE', 'label' => __('Reunion')],
            ['code' => 'RO', 'label' => __('Romania')],
            ['code' => 'RU', 'label' => __('Russian Federation')],
            ['code' => 'RW', 'label' => __('Rwanda')],
            ['code' => 'BL', 'label' => __('Saint Barthelemy')],
            ['code' => 'SH', 'label' => __('Saint Helena')],
            ['code' => 'KN', 'label' => __('Saint Kitts and Nevis')],
            ['code' => 'LC', 'label' => __('Saint Lucia')],
            ['code' => 'MF', 'label' => __('Saint Martin')],
            ['code' => 'PM', 'label' => __('Saint Pierre and Miquelon')],
            ['code' => 'VC', 'label' => __('Saint Vincent and Grenadines')],
            ['code' => 'WS', 'label' => __('Samoa')],
            ['code' => 'SM', 'label' => __('San Marino')],
            ['code' => 'ST', 'label' => __('Sao Tome and Principe')],
            ['code' => 'SA', 'label' => __('Saudi Arabia')],
            ['code' => 'SN', 'label' => __('Senegal')],
            ['code' => 'RS', 'label' => __('Serbia')],
            ['code' => 'SC', 'label' => __('Seychelles')],
            ['code' => 'SL', 'label' => __('Sierra Leone')],
            ['code' => 'SG', 'label' => __('Singapore')],
            ['code' => 'SX', 'label' => __('Sint Maarten (Dutch part)')],
            ['code' => 'SK', 'label' => __('Slovakia')],
            ['code' => 'SI', 'label' => __('Slovenia')],
            ['code' => 'SB', 'label' => __('Solomon Islands')],
            ['code' => 'SO', 'label' => __('Somalia')],
            ['code' => 'ZA', 'label' => __('South Africa')],
            ['code' => 'GS', 'label' => __('South Georgia and Sandwich Isl.')],
            ['code' => 'SS', 'label' => __('South Sudan')],
            ['code' => 'ES', 'label' => __('Spain')],
            ['code' => 'LK', 'label' => __('Sri Lanka')],
            ['code' => 'SD', 'label' => __('Sudan')],
            ['code' => 'SR', 'label' => __('Suriname')],
            ['code' => 'SJ', 'label' => __('Svalbard and Jan Mayen')],
            ['code' => 'SZ', 'label' => __('Swaziland')],
            ['code' => 'SE', 'label' => __('Sweden')],
            ['code' => 'CH', 'label' => __('Switzerland')],
            ['code' => 'SY', 'label' => __('Syrian Arab Republic')],
            ['code' => 'TW', 'label' => __('Taiwan')],
            ['code' => 'TJ', 'label' => __('Tajikistan')],
            ['code' => 'TZ', 'label' => __('Tanzania')],
            ['code' => 'TH', 'label' => __('Thailand')],
            ['code' => 'TL', 'label' => __('Timor-Leste')],
            ['code' => 'TG', 'label' => __('Togo')],
            ['code' => 'TK', 'label' => __('Tokelau')],
            ['code' => 'TO', 'label' => __('Tonga')],
            ['code' => 'TT', 'label' => __('Trinidad and Tobago')],
            ['code' => 'TN', 'label' => __('Tunisia')],
            ['code' => 'TR', 'label' => __('Turkey')],
            ['code' => 'TM', 'label' => __('Turkmenistan')],
            ['code' => 'TC', 'label' => __('Turks and Caicos Islands')],
            ['code' => 'TV', 'label' => __('Tuvalu')],
            ['code' => 'UG', 'label' => __('Uganda')],
            ['code' => 'UA', 'label' => __('Ukraine')],
            ['code' => 'AE', 'label' => __('United Arab Emirates')],
            ['code' => 'GB', 'label' => __('United Kingdom')],
            ['code' => 'US', 'label' => __('United States')],
            ['code' => 'UM', 'label' => __('United States Outlying Islands')],
            ['code' => 'UY', 'label' => __('Uruguay')],
            ['code' => 'UZ', 'label' => __('Uzbekistan')],
            ['code' => 'VU', 'label' => __('Vanuatu')],
            ['code' => 'VE', 'label' => __('Venezuela')],
            ['code' => 'VN', 'label' => __('Vietnam')],
            ['code' => 'VG', 'label' => __('Virgin Islands, British')],
            ['code' => 'VI', 'label' => __('Virgin Islands, U.S.')],
            ['code' => 'WF', 'label' => __('Wallis and Futuna')],
            ['code' => 'EH', 'label' => __('Western Sahara')],
            ['code' => 'YE', 'label' => __('Yemen')],
            ['code' => 'ZM', 'label' => __('Zambia')],
            ['code' => 'ZW', 'label' => __('Zimbabwe')],
        ];
        parent::__construct($attributes);
    }
}
